### ISSUE TITLE
Remove unused imports now that the S3 stuff has it's own files

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#18]
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/app.js#L13

**Comment by JZPoteat** [comment]
Removed line 13

**Comment by bookcasey** [comment]
Did you also remove 14 and 15, other things we aren't using in this file?
