### ISSUE TITLE
All tables are singular except 'users'

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#19]
'user' is a reserved work in postgres, so I'm guessing when we tried to make a table called 'user' it threw it an error, and we made it plural. That said, all of the rest of our tables use a singular naming convention like 'client', 'company', 'photo', etc. A way around this would be to call the table 'myclientele_users'. 

@JZPoteat Don't make this change right now, but it's something we should do before turning the project in.

**Comment by JZPoteat** [comment]
Changed the database to use myclientele_user instead of users
