### ISSUE TITLE
Remove unncessary dependencies from package.json

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#20]
Path is part of node (https://nodejs.org/api/path.html) so we don't need to install it separately:
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/package.json#L30

We use postgrator-cli to run the migrations on heroku, so we can remove the second instance of it from dev dependencies:

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/master/package.json#L40

**Comment by JZPoteat** [comment]
Removed line 30 in package.json
