### ISSUE TITLE
Clean up S3 router

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#21]
Move bucket name into config.js/env variables so it's configurable:
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/s3/s3-router.js#L10

Remove unused variables like `key` and `'directory`: 
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/s3/s3-router.js#L12

This option is in seconds not milliseconds, so we could probably get away with 60 or less as we make the request for the singed url and then immediately PUT the photo on the frontend:
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/s3/s3-router.js#L18

**Comment by JZPoteat** [comment]
Didn't we use key in the then statement after getting the signed url?

`  const key = `${directory}/${uuid.v4()}`;
  return s3
    .getSignedUrlPromise('putObject', {
      Bucket: bucket,
      Key: name,
      ContentType: type,
      Expires: 30000,
    })
    .then((uploadUrl) => res.json({ url: uploadUrl, file_name: key }))
    .catch(error => res.json({error}));
});`

**Comment by bookcasey** [comment]
We are passing it to the client, but the client isn't using it

https://github.com/thinkful-ei-orka/myclientele-f5-client/blob/master/src/components/TakeReport/TakeReport.js

**Comment by JZPoteat** [comment]
Resolved
