### ISSUE TITLE
Remove duplicate imports of express

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#22]
We're already importing express in like 2, so it would be better to add `query` to line 2 than import it a second time:

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L6

`const express, { query } = require('express')` might work not sure, an alternative is just create a new variable like:
`const query = express.query;` rather than importing express again.

**Comment by JZPoteat** [comment]
Removed line 6 report-router.js
