### ISSUE TITLE
Use `transaction` when posting multiple things

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#23]
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L53-L69

Very common issue here. What happens if one of the photos fail to INSERT? Well, currently the report will still be created, butmaybe the user will get an error that it didn't work. To solve this problem, use `transaction` from knex: http://knexjs.org/#Builder-transacting

We've seen examples from this before in the helpers for seeding the database for the tests https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/master/test/test-helpers.js#L18

**Comment by bookcasey** [comment]
Related: https://github.com/thinkful-ei-orka/myclientele-f5-api/issues/24

**Comment by JZPoteat** [comment]
Issue resolved by prepping photos, the making db transaction function in photo-service (insertPhotos());.
