### ISSUE TITLE
Async issues with checking report fields

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#25]
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L106-L115

is not inside the `then` block started here:

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L89

Meaning, if the check to see if the id's match is slow enough, we could potentially just skip it and update someone else's report

**Comment by bookcasey** [comment]
Same issue in the delete route: https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L124

**Comment by bookcasey** [comment]
Two birds with one stone if you fix this issue: https://github.com/thinkful-ei-orka/myclientele-f5-api/issues/26

**Comment by JZPoteat** [comment]
Issue fixed by changing route to use async await instead of promise statements.
