### ISSUE TITLE
Duplicate databse calls in GET, PUT, and DELETE

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#26]
You don't need to make an additional call to the database here (and in several other places in this file): 

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L77

Because we are already adding the report info to the req object here: 
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L156

with this line of middleware:

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L156

**Comment by JZPoteat** [comment]
changed
