### ISSUE TITLE
Any authenticated user can edit any other users' clients

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-api#28]
https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/client/client-router.js#L75

We authenticate a user, but we don't ensure that they are only allowed to get/edit/delete only the clients that they own.

The easiest fix might be to add some logic here: 

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/client/client-router.js#L135-L151

To not only check if they exist, but ensure that the client they are getting belongs to them.

Get `/clients` solves this by making the SELECT with a WHERE clause that locks it down to the specific authenticated user:

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/client/client-service.js#L3-L9

That's another option.

**Comment by bookcasey** [comment]
Any authenticated user can get any company as well: https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/companies/companies-service.js#L4

**Comment by bookcasey** [comment]
Similar issue with photos, any authenticated user can get all photos for a report as long as they have the report id https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/photo/photo-service.js#L5

**Comment by JZPoteat** [comment]
The company route was intentionally left public because it was going to possibly be used during the user registration.  The client route should be fixed and the photo-router has been deleted.  It is not being used at the moment
